[tool.poetry]
name = "reactpy-dashboard"
version = "0.1.0"
description = ""
authors = ["Steve Jones <jonesst2608@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11.0"

reactpy = "^1.0.2"
reactpy-router = {version = "^0.1.1", source = "pypicloud"}
fastapi = "0.96.0"
uvicorn = "0.22.0"
pydantic = " 1.10.13"
reactpy-apexcharts = {version = "0.0.3", source = "pypicloud"}
reactpy-github-buttons = "^0.0.4"

[tool.poetry.group.dev.dependencies]

annotated-types = "0.6.0"
playwright = "1.34.0"
pytest-asyncio = "0.21.1"
pytest-mock = "3.12.0"
pytest-rerunfailures = "12.0"
pytest-timeout = "2.2.0"
python-dotenv = "1.0.0"
responses = "0.24.1"
sanic-cors = "2.2.0"
sanic-testing = "23.6.0"
pytest-playwright = "^0.4.3"
autoflake = "^2.2.1"


[[tool.poetry.source]]
name = "pypicloud"
url = "http://debian-server:6543/simple/"
priority = "supplemental"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
