[tool.poetry]
name = "reactpy-dashboard"
version = "0.1.0"
description = ""
authors = ["Steve Jones <jonesst2608@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
reactpy = "^1.0.2"
fastapi = "^0.103.0"
uvicorn = {extras = ["standard"], version = "^0.24.0"}
pytest-asyncio = ">=0.17"


[tool.poetry.group.dev.dependencies]
pytest = ">= 7.1.3, < 8.0.0"
pytest-env = "1.0.1"
httpx = ">=0.23.0,<0.25.0"
pytest-playwright = "^0.4.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
